# Database Configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/stockverdict2
spring.datasource.username=postgres
spring.datasource.password=kelvin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mudugudu974@gmail.com
spring.mail.password=urrjvuprbjgvyzrq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.user.password=Test12345_
spring.security.user.name=henriette

# ReCAPTCHA Configuration
recaptcha.secret.key=6LeuOnosAAAAAP1YyrYnvdmXxi-GZ0AUJuk3ozEg

# App Configuration
app.name=StockVerdict
app.version=1.0
app.environment=development

# Server Configuration
server.port=8080

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000
